- README.md
- processes/releases.md
Just need one of you to accept the PR since we already agreed on this mission and Tommy reviewed it, thanks.
> add our mission

- README.md
- processes/releases.md
Please add any commit to make it better, I wasn't super inspired!
> Better README intro

- assets/information.md
My two cents, feel free to take it or leave it 😄
> Change wording

- assets/information.md
Closes #225
Thanks for the edits @fharper !
> Rewrite long description

- events/charlotte.md
- Avoided personal information
- Avoided Social media links
> Charlotte speaker page

- opensource.md
> first draft on open source at MeiliSearch

- communication/post_forecast.md
Update the post forecast to add Firebase `Link` and `Status`.
**Note**: I didn't have the `ETA`
> Update forecast post for Firebase

- communication/post_forecast.md
Addition of a week on ETA because of my OOO.
> Update the ETA of Firebase guide

- communication/post_forecast.md
@meilisearch/docs-team Strapi tutorial part 1 ready for review
> Change status of Strapi tutorial

- communication/post_forecast.md
Update launch date for Aloglia guide and status for Firebase guide
@alallema @meilisearch/docs-team 
> Firebase guide status & Algolia guide date update

- communication/post_forecast.md
> Add status options to post forecast file

- communication/post_forecast.md
Update Algolia migration guide date
@meilisearch/docs-team 
> Update Algolia migration guide date

- communication/post_forecast.md
> Remove id field on unpublished content

- communication/post_forecast.md
- New ETA for next newsletter: May 30
- Product Hunt desc + Cloud public launch blog post delayed
- Added Laurene's blog post on our offsite, to be included in next newsletter
Fixes #<issue_number>
> Few updates on the forecast

- communication/post_forecast.md
> add forecast for e-commerce blog post

- communication/post_forecast.md
> Update migration guides status in post forecast

- communication/post_forecast.md
> Update status for e-commerce blog post to writing in progress

- communication/post_forecast.md
- Updated tentative publication date of the Firebase tutorial cc @alallema 
- Moved the `Instant Meilisearch` blog post to the published section cc @CaroFG
- Updated tentative publication date of the Cloud getting started guide cc @oluademola
- Updated tentative publication date of the Product Hunt -related content
Fixes #<issue_number>
> a few different updates - see the PR content

- process/blog_publishing_process.md
> Add instruction about tags

- communication/post_forecast.md
> Add Rails+React update post

- process/blog_publishing_process.md
> Add corrections section to publishing process

- process/release_process.md
> Add release process

- communication/post_forecast.md
Hey team!
Here is the post forecast update about my article about Docker.
> Add Docker article to post forecast

- process/release_process.md
> Add demos css theme to release process

- guidelines/url_guidelines.md
Fixes #454 
Adds best practices for SEO-friendly URLs
> Add URL best practices

- guidelines/tag_guidelines.md
- guidelines/tags.md
- process/blog_publishing_process.md
Fixes #466 
- Lists accepted blog tags + description
- Updates processes referring to tags
- Gives guidelines on how to use tags
> Blog tag guidelines

- guidelines/excerpt_guidelines.md
- process/blog_publishing_process.md
Fixes #453 
- Creates excerpts guidelines
- Updates blog publishing process
> Add excerpt guidelines
